### ISSUE TITLE
Update npm repo

### ISSUE THREAD

**Issue by AlexMoroz** [Ziv-Barber/officegen#111]
Is there a reason why you don't update the npm repo?
https://www.npmjs.com/package/officegen

**Comment by Ziv-Barber** [comment]
I'm not happy with the charts code but I can do it anyway because the other
stuff working fine.
I'll do that later today.

Ziv

**Comment by Ziv-Barber** [comment]
Version 0.2.10 is out.

**Comment by AlexMoroz** [comment]
Thank you!

**Comment by holm** [comment]
0.2.10 causes a lot of our tests to fail. I have yet to figure out what causes this, since I have trouble getting a good stacktrace. I was trying to see if I could spot the change that caused this, but I can see there are a ton of changes over 2 years.

I will try to figure out the cause of the issue and report that separately, but I think it would have been prudent to release this as a minor instead of a patch, given the very big changes.
