### ISSUE TITLE
TypeError: object (callback();) is not a function   /officegen/lib/genpptx.js:1561:6

### ISSUE THREAD

**Issue by johnlo1992** [Ziv-Barber/officegen#65]
genpptx.js has a function callback(); that is not declared in genpptx.js

error occurs after executing " node make_pptx.js"

cheers

**Comment by pietersv** [comment]
Sorry about that.  The issue is that the second argument to `slide.addChart` is dropped.

`slide.addChart(chartInfo, null, callback, callback);` should now be 
`slide.addChart(chartInfo, callback, callback);`

I had updated the README and the `test/` files but missed the example.   Submitting a PR that fixes this, and separates `examples/make_pptx.js` into two files, one that generates charts and one that doesn't.

**Comment by johnlo1992** [comment]
Ah ok, no worries. Thanks for your help!
